export const plans = [
  {
    name: "Emprendedor",
    price: "$15.000",
    period: "pago único",
    description: "Tienda Básica. Pensada para emprendedores que recién comienzan.",
    features: [
      "Subdominio o subdirectorio dedicado",
      "Personalización sencilla: logo, colores, redes",
      "Carga de productos básicos con imágenes, precios y descripciones",
      "Integración con pasarelas de pago",
      "Página de contacto o WhatsApp directo",
      "Dashboard minimalista",
    ],
    cta: "Empezar Ahora",
    popular: true,
    disabled: false,
  },
  {
    name: "Profesional",
    price: "Próximamente",
    period: "",
    description: "Perfecto para negocios en crecimiento que necesitan más potencia y herramientas.",
    features: [
      "Hasta 5 Tiendas Online",
      "Productos Ilimitados",
      "Soporte Prioritario 24/7",
      "Analíticas Avanzadas",
      "Herramientas de Marketing IA",
    ],
    cta: "Próximamente",
    popular: false,
    disabled: true,
  },
  {
    name: "Corporativo",
    price: "Próximamente",
    period: "",
    description: "La solución completa para empresas que gestionan múltiples marcas y equipos.",
    features: [
      "Tiendas Ilimitadas",
      "Productos Ilimitados",
      "Soporte Dedicado",
      "Acceso a API",
      "Roles de Usuario Avanzados",
    ],
    cta: "Próximamente",
    popular: false,
    disabled: true,
  },
];